version = 0.1

[default.deploy.parameters]
stack_name = "NimoBackendStack"
region = "ap-southeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = false
resolve_s3 = true
