AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    Timeout: 10
    Runtime: nodejs20.x
    Environment:
      Variables:
        DYNAMO_TABLE: CryptoSearchHistory
        EMAIL_FROM: "your-ses-verified-email@example.com"

Resources:
  GetCryptoPriceFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: getCryptoPrice.handler
      Policies:
        - AmazonDynamoDBFullAccess
        - AmazonSESFullAccess
      Events:
        Api:
          Type: Api
          Properties:
            Path: /crypto
            Method: post

  GetSearchHistoryFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: getSearchHistory.handler
      Policies:
        - AmazonDynamoDBReadOnlyAccess
      Events:
        Api:
          Type: Api
          Properties:
            Path: /history
            Method: get

  CryptoSearchTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: CryptoSearchHistory
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAYPERREQUEST