AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    Timeout: 10
    Runtime: nodejs20.x
    Environment:
      Variables:
        DYNAMO_TABLE: CryptoSearchHistory
        EMAIL_FROM: "dhekeujju@gmail.com"

Resources:
  ServerlessRestApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Stage
      Cors:
        AllowMethods: "'GET,POST,OPTIONS'"
        AllowHeaders: "'*'"
        AllowOrigin: "'*'"
  GetCryptoPrice:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./dist
      Handler: app-getCryptoPrice.handler
      Policies:
        - AmazonDynamoDBFullAccess
        - AmazonSESFullAccess
      Events:
        Api:
          Type: Api
          Properties:
            Path: /crypto
            Method: post
            RestApiId: !Ref ServerlessRestApi

  GetSearchHistory:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./dist
      Handler: app-getSearchHistory.handler
      Policies:
        - AmazonDynamoDBReadOnlyAccess
      Events:
        Api:
          Type: Api
          Properties:
            Path: /crypto/history
            Method: get
            RestApiId: !Ref ServerlessRestApi

  
            

  CryptoSearchTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: CryptoSearchHistory
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

Outputs:
  ApiEndpoint:
    Description: "Api endpoints"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Stage"